name: ci

on:
  pull_request:

jobs:
  pre-commit:
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: pre-commit/action@v3.0.1
      with:
        extra_args: >
          --from-ref ${{ github.event.pull_request.base.sha || github.event.before }}
          --to-ref HEAD
